### ISSUE TITLE
Add column to a table after start the process

### ISSUE THREAD

**Issue by linanh** [bersler/OpenLogReplicator#1]
Add column to a table after start the proccess, and then insert the table, the process will be terminated.
Error: signal 11
./OpenLogReplicator[0x41b5e1]
/lib64/libc.so.6(+0x363f0)[0x7f4f1ed0a3f0]
/lib64/libstdc++.so.6(_ZNSsC1ERKSs+0x1b)[0x7f4f1f678f7b]
./OpenLogReplicator[0x4093f0]
./OpenLogReplicator[0x43bf21]
./OpenLogReplicator[0x435a5c]
./OpenLogReplicator[0x43697a]
./OpenLogReplicator[0x427c0a]
./OpenLogReplicator[0x43984a]
/lib64/libpthread.so.0(+0x7ea5)[0x7f4f22a21ea5]
/lib64/libc.so.6(clone+0x6d)[0x7f4f1edd28cd]

**Comment by bersler** [comment]
Alter table is not supported. The program should not crash but just ignore DML commands after the alter. This ha been fixed with the latest commit.

**Comment by bersler** [comment]
Issue fixed

**Comment by linanh** [comment]
Using the latest code, can't capture the change of  the alter table, even restart the program.
When capture the event "alter", and then refresh the table columns?

**Comment by bersler** [comment]
Yes, because ALTER TABLE is not supported. What you can do is switch logfile and reset replication (for example, delete the checkpoint JSON file). OpenLogReplicator will resume replication with the new schema and starting from a fresh redo log file.
