### ISSUE TITLE
ERROR: transaction does not exists in hash map1

### ISSUE THREAD

**Issue by linanh** [bersler/OpenLogReplicator#10]
Hi, @bersler . 
Using latest version program, the program show "ERROR: transaction does not exists in hash map1" and then exit.

**Comment by bersler** [comment]
Hi @linanh,Can you send me a reproduction of this error? Please check the manual page for reproduction instructions.Regards,Adam31 lip 2020 10:23 linanh <notifications@github.com> napisał(a):
Hi, @bersler .
Using latest version program, the program show "ERROR: transaction does not exists in hash map1" and then exit.

**Comment by linanh** [comment]
I remove the checkpoint file and increase memory-max-mb, then the program is normal. 
But I forgot to remeber the log name, wait the issue occur again.

**Comment by bersler** [comment]
I have added some debug information for further analysis. But hitting the bug again it is very hard to find the actual place in code which is wrong. If it occurs again - please let me know @linanh.

**Comment by linanh** [comment]
Hi @bersler.  
The error occur again, i found that these exist two or more same delete sql for one row using logminer parse redolog.
Because the privacy reason, i can't send the redolog file. The version of oracle is 11.2.0.3
Thanks.

**Comment by bersler** [comment]
What do you mean? Are you talking about 2 processes simultaneously executing exactly the same dml command - one would succeed and the other would fail and rollback? I will try this scenario. But currently without any test confirming the fix is good I am not able to correct the fault.

**Comment by linanh** [comment]
Analyze the redolog using logminer, the result show the two or more same delete sql with the same ROWID exist in the same transaction ( xid is same ).

**Comment by caodongzhi1976** [comment]
Hi, @bersler .
Can the program rebuild the schema at runtime during replicating，without restart the program. Because the table struct can be modified during the program is running.

**Comment by bersler** [comment]
Hi @caodongzhi1976,
This question is not related to error, please discuss this subject on a separate topic.

**Comment by bersler** [comment]
Hi @linanh, I have fixed one place where there could be error in transaction chain processing. Please check if that is a fix to the problem you have.

**Comment by linanh** [comment]
Now, it works well.
