### ISSUE TITLE
leak of Check Point

### ISSUE THREAD

**Issue by caodongzhi1976** [bersler/OpenLogReplicator#12]
Hi,

Our Oracle has two Arch threads. the Arch file sequence is below.

thread_1_seq_50219.3285.1051090681	
thread_2_seq_42952.3286.1051091023	
thread_1_seq_50220.3287.1051091323	
thread_2_seq_42953.3288.1051091637	
thread_1_seq_50221.3289.1051091977	
thread_2_seq_42954.3290.1051092267

But the scn sequence is out of order.
So the Check Point is no use. I think, we should have one Check Point per thread.
The scn sequence in the attach file, which is a xlsx file.

[scn.xlsx](https://github.com/bersler/OpenLogReplicator/files/5228836/scn.xlsx)

**Comment by bersler** [comment]
Hi @caodongzhi1976. You are right. Handling multiple arch threads is not supported yet. I have added a note to the documentation - added to list of unsupported features. Thank you for your not about this.
