### ISSUE TITLE
Add pseudo ROW_ID for DML-based events.

### ISSUE THREAD

**Issue by Naros** [bersler/OpenLogReplicator#127]
In the upstream Debezium project, we have a user request to include the synthetic ROW_ID value as part of the DML payloads.  We can do this with LogMIner and this should be equally easy to do for OpenLogReplicator.

**Comment by bersler** [comment]
This is already implemented:
https://github.com/bersler/OpenLogReplicator/blob/master/documentation/reference-manual/reference-manual.adoc
You need to set 'rid': 1

**Comment by Naros** [comment]
Awesome thanks @bersler, I must have missed that :+1:
