### ISSUE TITLE
How to extract Oracle redo logs remotely

### ISSUE THREAD

**Issue by huahuaxu** [bersler/OpenLogReplicator#13]
Do you know any way to extract Oracle redo logs remotely？

**Comment by bersler** [comment]
You are right, the documentation is missing. Because there are significant changes in progress it is not yet created. I will update this issue when it is finished.

**Comment by huahuaxu** [comment]
Do you mean that it will be supported in the future?

**Comment by bersler** [comment]
What kind of promises do you expect? Wishful thinking? What is future? What do you mean remotely? This project has not yet reached GA. This is not a best place to make a general discussion.

**Comment by bersler** [comment]
Hi @huahuaxu , I have added another page to the manual describing modes of work for OpenLogReplicator: https://www.bersler.com/openlogreplicator/getting-started/modes-of-operation/
