### ISSUE TITLE
Include `owner` in DDL changelog of non-table objects

### ISSUE THREAD

**Issue by hbk671104** [bersler/OpenLogReplicator#135]
**Is your feature request related to a problem? Please describe.**

I'm using OLR by integrating debezium into my project. I found the `owner` key missing in the DDL changelog of non-table objects.

**Describe the solution you'd like**

Include the `owner` key and possibly a key that specifies the object's name in the DDL changelog of non-table database object.

**Describe alternatives you've considered**

None.

**Additional context**

<img width="791" alt="企业微信截图_17158312332818" src="https://github.com/bersler/OpenLogReplicator/assets/5074788/94229f4e-84fd-4469-8498-355e8749e1f1">

**Comment by bersler** [comment]
This issue has low priority. Parsing the owner would require to add code to parse every type of DDL object. This seems to be a feature which most like would not be a must have for other users.

**Comment by hbk671104** [comment]
> This issue has low priority. Parsing the owner would require to add code to parse every type of DDL object. This seems to be a feature which most like would not be a must have for other users.

We finished our own implementation. We'll submit a PR soon.

**Comment by hbk671104** [comment]
#151 PR submitted.

**Comment by bersler** [comment]
Actually this is done with one of some last commits. DDL operations include schema name now.

**Comment by bersler** [comment]
@hbk671104 if you are happy with the solution - a donation is a good way to show your happiness :)
