### ISSUE TITLE
Missing oci.h and  -lclntshcore -lnnz19 -lclnth

### ISSUE THREAD

**Issue by mydeveloperday** [bersler/OpenLogReplicator#14]
While building on ubuntu, (having installed the 19.3 instant client from the rpm from oracle with alien -i), 

OpenLogReplicator won't build with out some manual intervention, Is this a standard oracle client environment to have?

<path_to_oracle_client>/sdk/include for the includes?
<path_to_oracle_client> for the libs?

Following the rpm installation the includes are in

/usr/include/oracle/19.3/client64/

and the link libraries are in 

/usr/lib/oracle/19.3/client64/lib/

This can't be handled with a single with_instantclient

```
if test "${with_instantclient+set}" = set; then :
  withval=$with_instantclient; 
  CPPFLAGS="-I$withval/sdk/include -DLINK_LIBRARY_OCI $CPPFLAGS"; 
   LDFLAGS="-L$withval -lclntshcore -lnnz19 -lclntsh $LDFLAGS"
fi
```

In the end I modified this line to be (to get past the need to make symbolic links)
`+  withval=$with_instantclient; CPPFLAGS="-I$withval -DLINK_LIBRARY_OCI $CPPFLAGS"; LDFLAGS="-L/usr/lib/oracle/19.3/client64/lib -lclntshcore -lnnz19 -lclntsh $LDFLAGS`"

It would be nice if the configure script could handle a "semi" standard installation.

**Comment by bersler** [comment]
I have tested a bit compilation with Ubuntu and made compilation work. Currently fix is applied to nightly branch. I will also submit the fix to master branch. Currently the only requirement for the Oracle libraries is to make one additional symlink:
unzip instantclient-basic-linux.x64-19.10.0.0.0dbru.zip
unzip instantclient-sdk-linux.x64-19.10.0.0.0dbru.zip
cd instantclient_19_10
ln -s libclntshcore.so.19.1 libclntshcore.so
Currently testing with Oracle client 19.10. Although this symlink is not present in Oracle libraries, it allows easy to switch between clients without any modification in the code.
