### ISSUE TITLE
For the table SYS.SMON_SCN_TIME, there are different result between DBMS_LOGMNR and OpenLogReplicator

### ISSUE THREAD

**Issue by huahuaxu** [bersler/OpenLogReplicator#15]
when analysing the redo log of table SYS.SMON_SCN_TIME, I find that:
1.by DBMS_LOGMNR, the table SYS.SMON_SCN_TIME has 9 columns;
2.by OpenLogReplicator, the table SYS.SMON_SCN_TIME has 8 columns;
do you known the reason?

**Comment by bersler** [comment]
No idea. How many columns does the schema actually have? Which is missing?

**Comment by huahuaxu** [comment]
the result of DBMS_LOGMNR is correct.

**Comment by bersler** [comment]
I don't agree, I think the result of OpenLogReplicator is correct - will you write more details or should I guess what is the difference?

**Comment by huahuaxu** [comment]
you are right，the missing column values are in the supplemental log area. 
thanks!
