### ISSUE TITLE
Can't Parse some message

### ISSUE THREAD

**Issue by yintongkai** [bersler/OpenLogReplicator#166]
**A brief description of the bug.**
     When I was collecting data from oracle(19c), an alarm message appeared  and the message was not sent to kafka.
Warnings:
    code 60025: "file: <file name> - block: <number> - invalid header checksum, expected: <number>, calculated: <number>"
    code 60017: "minimal supplemental log missing or redo log inconsistency for transaction <xid>"
    code 50065: "empty attributes for XID: <xid>"
**Is the bug present on the latest master branch.**
   I don't know,but i used 1.6.0 branches.

**Describe steps required to reproduce the bug.**
oracle environment:
   oracle 19.0.0.0 
   pdb
   not rac and not asm. 
   user:sys. The other party only provides the system user, I added the code to support the system user.
   remote file system: nfs

**Comment by bersler** [comment]
OpenLogReplicator is parser for redo log data. You have just reported that it fails to parse your redo logs, but you did not provide the redo logs and the error log and the checkpoint files. Please submit those, you can sent me to my email it you don't want to sent to public.

**Comment by yintongkai** [comment]
{
  "version": "1.6.0",
  "dump-redo-log": 1,
  "dump-raw-data": 0,
  "dump-path": "/home/hive/OpenLogReplicator/dump_log",
  "log-level": 4,
  "trace": 7968,
  "source": [
    {
      "alias": "S1",
      "name": "O112A",
      "reader": {
        "type": "online",
        "path-mapping": ["/archivelog","/home/hive/oracle_map_data/archivelog","/oradata/orcldg/onlinelog","/home/hive/oracle_map_data/onlinelog"],
        "user": "sys",
        "password": "*******",
        "server": "//***.***.***.*:1521/***",
        "host-timezone": "+08:00",
        "log-timezone": "+08:00",
        "db-timezone": "+08:00"
      },
      "format": {
        "type": "json",
        "column": 2,
        "message": 1
      },
      "arch": "online",
      "flags": 0,
      "memory": {
        "min-mb": 64,
        "max-mb": 1024
      },
      "filter": {
        "table": [
          {"owner": "USER_A", "table": "TABLE_A"}
        ]
      }
    }
  ],
  "target": [
    {
      "alias": "K1",
      "source": "S1",
      "writer": {
        "type": "kafka",
        "topic": "O112A_PROGRESS_NOTE",
        "max-message-mb": 500,
        "properties": {
          "bootstrap.servers": "10.0.1.104:6667",
          "enable.idempotence": "false",
          "queue.buffering.max.messages": "200000"
        },
        "poll-interval-us": 100000,
        "queue-size": 65536
      }
    }
  ]
}

**Comment by yintongkai** [comment]
[logAndcheckpoint.tar.gz](https://github.com/user-attachments/files/16517139/logAndcheckpoint.tar.gz)

**Comment by yintongkai** [comment]
The logdump files are created,but the file is too big. If necessary, I can find a single scn dump information and copy it to you.

**Comment by bersler** [comment]
Hi @yintongkai, as mentioned above, redo log files are needed, not logdump. Please follow the [contributing guidelines](https://github.com/bersler/OpenLogReplicator/blob/a16ac3b7f7d2e825c19b20063f6cfeb7be39a6bd/CONTRIBUTING.md).

**Comment by yintongkai** [comment]
Hi @bersler ,I have sent the redolog files to you. Please check your email.

**Comment by bersler** [comment]
Hi @yintongkai , did you receive my reply? Need help with reproduction of this issue.

**Comment by yintongkai** [comment]
Dear Adam Leszczyński,
I‘m so sorry!I have taken a break from this work because of other demands.
Because I was using the hospital's oracle backup library, which was only 
open for a while, the resources have now been recycled.I can't get those 
configuration parameters anymore.
I'm sorry I can't provide it now

**Comment by yintongkai** [comment]
Dear Bersler,
I‘m so sorry!I have taken a break from this work because of other demands.
Because I was using the hospital's oracle backup library, which was only 
open for a while, the resources have now been recycled.I can't get those 
configuration parameters anymore.
I'm sorry I can't provide it now
