### ISSUE TITLE
unsupported for table names longer than 30 characters

### ISSUE THREAD

**Issue by lililill** [bersler/OpenLogReplicator#176]
Oracle logminner unsupport for table names longer than 30 characters
Refer to the following article:
https://docs.oracle.com/en/database/oracle/oracle-database/21/sutil/oracle-logminer-utility.html#GUID-7594F0D7-0ACD-46E6-BD61-2751136ECDB4
https://stackoverflow.com/questions/61104335/in-oracle-12c-r2-does-logminer-support-table-column-names-longer-than-30-charact

Also after testing OpenLogReplicator unsupport for table names longer than 30 characters,when table names longer than 30 characters,it has no output
Is there any way to solve this problem
Thank you!

**Comment by bersler** [comment]
Please don't use bank issues for reporting bugs.
