### ISSUE TITLE
When a large amount of SQL is written every time, after about tens of thousands of entries, OpenLogReplicator does not work.

### ISSUE THREAD

**Issue by yetengfei** [bersler/OpenLogReplicator#24]
When a large amount of SQL is written every time, after about tens of thousands of entries, OpenLogReplicator does not work.
2021-07-08 14:34:16 [INFO] streaming to client
2021-07-08 14:34:16 [INFO] processing redo log: group: 1 scn: 212707636 to 0 seq: 1635 path: /data/oracle/oradata/orcl/redo04.log offset: 1024
2021-07-08 14:37:48 [INFO] processing redo log: group: 2 scn: 214834738 to 0 seq: 1636 path: /data/oracle/oradata/orcl/redo05.log offset: 1024

**Comment by yetengfei** [comment]
If it is "writer": {
"type": "file",
"name": "transactions.json",
"start-seq": 0
} Then there is no problem; if it is "writer": {
"type": "zeromq",
"uri": "tcp://0.0.0.0:50000"
} Or "writer": {
"type": "network",
"uri": "0.0.0.0:50000"
}Then it can only run more than 60,000, can I trouble you to check it out?

**Comment by bersler** [comment]
Can you provide a reproduction? What is large? I have tested transactions with 1M insert operations and all works fine.

**Comment by yetengfei** [comment]
yes,I User WriteFile is Ok,but when I use   WriteStream to write zeromq or network ,It Stop at  more than 60,000 message.

**Comment by yetengfei** [comment]
Can I help you see this problem

**Comment by bersler** [comment]
Last few versions had optimization which broke the protobuf code. I have made a few fixes in the version 0.9.18-beta.
Does the error still appear? I have tested with network protocol and transmitted 4.5M messages. And there was no problem. 
Can you please share some details how to reproduce the error?

**Comment by bersler** [comment]
Any update @yetengfei? Does bug still appear in latest version?

**Comment by bersler** [comment]
Details missing how to reproduce Issue.
