### ISSUE TITLE
ORA-01000: maximum open cursors exceeded

### ISSUE THREAD

**Issue by LoveChina-3000** [bersler/OpenLogReplicator#27]
**Below is the stack information：**
(gdb) bt
#0  OpenLogReplicator::DatabaseEnvironment::checkErr (this=0x602000005070, errhp=0x62c00000d4c8, status=-1) at DatabaseEnvironment.cpp:84
#1  0x00000000006d2354 in OpenLogReplicator::DatabaseStatement::executeQuery (this=0x6070000d6fc0) at DatabaseStatement.cpp:67
#2  0x000000000071a67a in OpenLogReplicator::ReaderASM::redoRead (this=0x6120000133c0, buf=0x6250000a5400 '\276' <repeats 200 times>..., offset=1, size=512) at ReaderASM.cpp:137
#3  0x000000000071af41 in OpenLogReplicator::ReaderASM::reloadHeaderRead (this=0x6120000133c0) at ReaderASM.cpp:156
#4  0x000000000056d6bc in OpenLogReplicator::Reader::reloadHeader (this=0x6120000133c0) at Reader.cpp:261
#5  0x00000000005731b9 in OpenLogReplicator::Reader::run (this=0x6120000133c0) at Reader.cpp:416
#6  0x000000000068c9a8 in OpenLogReplicator::Thread::runStatic (context=0x6120000133c0) at Thread.cpp:39
#7  0x00007ffff15daea5 in start_thread () from /lib64/libpthread.so.0
#8  0x00007fffef9a58dd in clone () from /lib64/libc.so.6
(gdb) c
Continuing.
2021-11-04 19:23:32 [ERROR] OCI ERROR: [ORA-01000: maximum open cursors exceeded]

**Comment by bersler** [comment]
ASM support is experimental and actually is not recommended to use. It will be removed from code. Please don't use it.
