### ISSUE TITLE
error:starting sequence if unknown, failing

### ISSUE THREAD

**Issue by waeilua** [bersler/OpenLogReplicator#29]
If the amount of data exceeds 500,000, the program will get an error:
[ERROR] starting sequence if unknown, failing
the config json set:
"type": "online",
and in the writer ,set "start-scn"

the tag:0.9.32-beta working well

**Comment by bersler** [comment]
Hi @waeilua,
Can you please share more details? How should I find a bug in the code based just on such description? What is 500 000? Is that number of archived redo log files? File size? Number of rows in transaction? Please share some redo log file which shows error or provide reproduction steps for this problem?
Regards,
Adam

**Comment by bersler** [comment]
Hi @waeilua, a gentle reminder to submit some details about the issue. If I receive nothing I will close this issue in 7 days.

**Comment by waeilua** [comment]
@bersler  Sorry, I forgot to follow this.
It happened to one of my test databases.

I am inserting test data into A table, and other data is being inserted into other tables at the same time.
I use time to get the scn, and then insert the data. When the data is inserted, I will set the start-scn in the writer, and then start to run the code to start the analysis.

When I finish inserting 30000 pieces of data first, and do the above steps, the code works fine.
But when I finish inserting 500000 pieces of data first and go through the above steps, the code works and the above error occurs.

The results of the code run are different, it seems to be related to the amount of inserted data.
At that time, I ran 0.9.32-beta, and there was no abnormal situation in the code work due to the different number of data.

**Comment by bersler** [comment]
I would need to reproduce this problem in my environment to understand what is the problem. For that I need:
a) a full list of SQL commands and other config files to step by step reproduce this issue using docker Oracle XE database
or
b) receive the redo log file or files with transactions; and if this is some big endian machine (AIX, Solaris) I would need also results of "ALTER SYSTEM DUMP LOGFILE <file>"

Otherwise this is a riddle for me and I will not be able to help.

**Comment by bersler** [comment]
Hi @waeilua, will you be able to send me some archived redo logs which reproduce this error? You can contact me by email if you don't want to put the redo log files with reproduction in public internet space. This is actually a preferred way by me.

**Comment by waeilua** [comment]
Hi @bersler  
I just passed the Chinese New Year, and the machine where the database used for testing is located actually accumulates a lot of logs and complex usage environments. I don’t know who else is using these machines except me.
I first provide the database version and table structure to your mailbox.

**Comment by waeilua** [comment]
Hi @bersler 
The mail has been sent to your , plz check it

**Comment by waeilua** [comment]
Hi @bersler  
I didn't check whether the log was overwritten before. I thought about it, this problem is limited to the inconsistent performance of the code between versions on the scn. I will carry out stricter environmental control and log inspection in a while, and test it again. Close first.
