### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by lihong12500** [bersler/OpenLogReplicator#3]
when I compile,Error message:

Building file: ../src/CommandBuffer.cpp
Invoking: Cross G++ Compiler
g++ -std=c++1y -I/opt/instantclient_11_2/sdk/include -I/opt/rapidjson/include -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/CommandBuffer.d" -MT"src/CommandBuffer.o" -o "src/CommandBuffer.o" "../src/CommandBuffer.cpp"
cc1plus: error: unrecognized command line option "-std=c++1y"
make: *** [src/CommandBuffer.o] Error 1

My server environment is redhat linux 6.8 server

Can you provide compilation conditions?thank you!

**Comment by bersler** [comment]
The code was had build options for C++1y which is available for Red Hat 7.
But actually the C++1y features were not used and it works fine with C++0x.
I have updated the code. Please try now.

**Comment by lihong12500** [comment]
Thank you for your reply to my question, I have updated the code，making error message:
oneday@dev:/data/goWork/dbtool/OpenLogReplicator/Debug>make
Building file: ../src/CommandBuffer.cpp
Invoking: Cross G++ Compiler
g++ -std=c++0x -I/opt/instantclient_11_2/sdk/include -I/opt/rapidjson/include -O0 -g3 -Wall -c -fmessage-length=0 -fsanitize=address -MMD -MP -MF"src/CommandBuffer.d" -MT"src/CommandBuffer.o" -o "src/CommandBuffer.o" "../src/CommandBuffer.cpp"
cc1plus: error: unrecognized command line option "-fsanitize=address"
make: *** [src/CommandBuffer.o] Error 1

G++ version information:
oneday@dev:/data/goWork/dbtool/OpenLogReplicator/Debug>g++ --version
g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

c++ version information:
oneday@dev:/data/goWork/dbtool/OpenLogReplicator/Debug>c++ --version
c++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I wish to consult you on a few questions:
1. I have a production environment, oracle 9i and oracle 10g, Operating system version have aix 5.2 or RedHat 4.8. When I use this code to compile whether or not it passes?
2. Historical data is very important, can you provide initialization data tools. thank you!

**Comment by bersler** [comment]
You need to have GCC newer version than 4.4. Preferably 4.8. It is best to compile on CentOS 7. Other wishes - please contact me directly or create feature requests.
