### ISSUE TITLE
Reading Redo logs directly

### ISSUE THREAD

**Issue by voultest** [bersler/OpenLogReplicator#30]
Can we read redo log files by passing them to openlogreplicator? Put in another way, without adding the oracle config params to the json file and only having redo logs can we read it with openlogreplicator? This is because the redo logs are dumped to a shared drive and we do not have access to the oracle servers?

**Comment by bersler** [comment]
Yes, this mode is also supported. The documentation is not yet up to date. I plan to update it when I have time.
