### ISSUE TITLE
The gcc version error

### ISSUE THREAD

**Issue by Gogo-scc** [bersler/OpenLogReplicator#32]
I had updated GCC to 4.9,But error
[root@kafka1 OpenLogReplicator]# ./src/OpenLogReplicator
2022-05-23 05:49:48 [INFO] OpenLogReplicator v.0.9.41-beta (C) 2018-2022 by Adam Leszczynski (aleszczynski@bersler.com), see LICENSE file for licensing information, linked modules: Kafka OCI
2022-05-23 05:49:48 [ERROR] binaries are build with no regex implementation, check if you have gcc version >= 4.9
[root@kafka1 OpenLogReplicator]# gcc --version
gcc (GCC) 4.9.0
Copyright © 2014 Free Software Foundation, Inc.

**Comment by bersler** [comment]
If the error appears - this means that the compiler you used has a regex implementation which is faulty. Please check newer gcc. Maybe you should use at least 5.0? I have not tested such old compiler, I would generally prefer something newer - or just use docker images for compilation.

**Comment by luss** [comment]
Centos 7 --> gcc v7.3
Centos 8 --> gcc v8.5
Centos 9 --> gcc v11.3

I suggest you build on a newer version of your OS.  Back in the day, I
rember you could build gcc from source and upgrade to a newer version
without upgrading the OS, but, I'm not sure you have a good reason to do
this.

**Comment by bersler** [comment]
Thanks @luss for good suggestion. I want to add that setting up custom complicated environments it not a good idea. If you find an error I would not have patience and time to recreate the same environment in my lab to help you. Please use docker images instead. The docker image contains all commands to compile both on Debian and CentOS so you are able to extract them and even compile the code manually if needed.

**Comment by luss** [comment]
Definitely agree w Adam.  Adam has worked very hard for several years to
make OLR be a well tested solution for the mission critical task it does.

**Comment by bersler** [comment]
Thanks @luss - in fact it does not make really sense to spend tens of hours to allow the code to be build with all possible compiler versions. This is waste of time. To be sure that actually all different compiler versions work I would need to repeat all test cases with all possible compiler versions. I would rather spent time on real work. We have Docker these days and you can just copy the compiled binary to any system. @Gogo-scc, in the future you can of course imagine to add support also some other OS-es like Solaris or AIX. If there is reasonable business justification of course. Today I really don't have such boxes so I can't phisically even check if the code compiles.
