### ISSUE TITLE
bug report: redolog parse fail in dg node

### ISSUE THREAD

**Issue by xbsura** [bersler/OpenLogReplicator#33]
![img_v2_29e0eebf-6441-4f3f-84cd-fa13326e96bg](https://user-images.githubusercontent.com/2181072/203941141-9595c18b-7dfa-4c13-9a47-99e4ab232932.jpg)

oracle version: 19c

OpenLogReplicator version: 0.8.9

any solution for this?

thanks

**Comment by bersler** [comment]
solution Is to update to latest version of OpenLogReplicator
