### ISSUE TITLE
ERROR: part transaction delete: not yet implemented

### ISSUE THREAD

**Issue by linanh** [bersler/OpenLogReplicator#4]
The proccess print the error logs:
ERROR: part transaction delete: not yet implemented

**Comment by bersler** [comment]
@linanh, can you send me a reproduction for this scenario? 
I have not implemented it yet, because I haven't built a test scenario to get this.

**Comment by linanh** [comment]
The error occured in a product environment database when i testing OpenLogReplicator.
But i don't known how to reproduce the data. I guess this error occured at  millions of record update in a single transaction.

**Comment by bersler** [comment]
If you came across this issue again - please send me a sample code which would generate it.

**Comment by linanh** [comment]
@bersler The error reappear in a single transaction:
step 1: insert about thirty thousand records to a table.
step 2: rollback

**Comment by linanh** [comment]
By the way, using the fixed redo buffer size cause high memory usage.

**Comment by bersler** [comment]
Thanks @linanh , I have been able to reproduce the error, I have just uploaded a first fix. It is not fully fixed so please use with caution. By the way, let's stick to one topic here.

**Comment by bersler** [comment]
Hi @linanh  support for out of order UNDO has been just implemented. Please check the latest commit.

**Comment by linanh** [comment]
Thanks @bersler , I will test it over the next days.
