### ISSUE TITLE
Feature: Add basic filtering of data

### ISSUE THREAD

**Issue by bersler** [bersler/OpenLogReplicator#41]
**Is your feature request related to a problem? Please describe.**
Very often a big table is replicated but contain just few rows which are needed for replication. There is no filtering available so currently when table is chosen for replication - all transactions related to this table would be sent to output.

**Describe the solution you'd like**
A simple filter for one or many columns would allow to select such rows. 

**Describe alternatives you've considered**
Make filtering on Kafka - but this requires to unnecessary process large volume of data.

**Additional context**
Filtering could be based on one, or many columns. Simple conditions for filters like AND and OR would be useful.

**Comment by bersler** [comment]
This feature is complicated to implement.. If there is a demand from users more focus could be given here.

**Comment by sonnguyen-dba** [comment]
Hi Adam,
I love this feature!

Regards,
Son

**Comment by bersler** [comment]
Thanks @sonnguyen-dba , I agree. I have seen many customer cases where the source table was big but the data which had to go to CDC was less than 1% of the traffic. Simple field filtering helped a lot here.

**Comment by bersler** [comment]
basic filtering is done with the latest commit
