### ISSUE TITLE
Feature: Allow dynamically change set of replicated tables

### ISSUE THREAD

**Issue by bersler** [bersler/OpenLogReplicator#44]
**Is your feature request related to a problem? Please describe.**
Start replication, add tables to replicated set of tables from another schema (not present during startup).

**Describe the solution you'd like**
If set of replicated tables changers, OpenLogReplicator would update the schema for new user not present before and resume replication.

**Describe alternatives you've considered**
Current workaround is to stop replication, delete checkpoint files, and restart (collecting whole schema again) with new configuration.

**Additional context**
Might be very usable when the set of replicated schemas is not known during program startup.

**Comment by bersler** [comment]
This feature is complicated to implement.. If there is a demand from users more focus could be given here.

**Comment by bersler** [comment]
Thanks @Son for feedback,

There are actually 2 cases here. When you start OpenLogReplicator (or use gencfg.sql) you define which schemas are observed. For those schemas all schema is extracted. So, you can later add or remove tables - but only if they origin from defined set of schemas. This is already implemented.

What is not implemented yet is feature to add more schemas to the list. The case, when you start replication defining just schema X, and later decide to replicate tables from schema Y. This is the case which this Incident refers to.

Regards,
Adam

**Comment by sonnguyen-dba** [comment]
Thanks @bersler,
Yes, I only add more tables - The origin from defined set of schemas.

Regards,
Son
