### ISSUE TITLE
Feature: Allow reload of OpenLogReplicator.json config file without restart

### ISSUE THREAD

**Issue by bersler** [bersler/OpenLogReplicator#53]
**Is your feature request related to a problem? Please describe.**
When the list of tables is updated, OpenLogReplicator needs to be restarted. Technically this should not be necessary. Instead it could just update the config file and continue replication with changed set of tables.

**Describe the solution you'd like**
Track changes in OpenLogReplicator.json config file. If file is changed, it would be loaded, and list of tables (or maybe other configuration parameters too) would be updated with new values.

**Describe alternatives you've considered**
Stop OpenLogReplicator. Update config. Start OpenLogReplicator.

**Additional context**
Stopping and starting again might be time consuming when there are large transactions. This causes delay in the replication stream.

**Comment by bersler** [comment]
This feature is complicated to implement.. If there is a demand from users more focus could be given here.

**Comment by sonnguyen-dba** [comment]
Hi Adam,
If this feature is not be very complex to implement. Can you help me this feature.

Regards,
Son

**Comment by bersler** [comment]
Thanks Son for feedback, this feature indeed might not be very complex to implement and might be required for #46, #47 or #48.

**Comment by sonnguyen-dba** [comment]
Tks Adam!

**Comment by sonnguyen-dba** [comment]
Thanks Adam for supported!

**Comment by bersler** [comment]
Implemented in 1.3.0
