### ISSUE TITLE
Feature: Add interface to produce metrics

### ISSUE THREAD

**Issue by bersler** [bersler/OpenLogReplicator#54]
**Is your feature request related to a problem? Please describe.**
Add ability to probe OpenLogReplicator process to provide statistics about processed work.

**Describe the solution you'd like**
Introduce a service which would provide monitoring statistics like number of processed transactions, used memory, biggest transaction, etc.

**Describe alternatives you've considered**
Track messages from the error log. But the provided information is not sufficient.

**Additional context**
Monitoring would allow to provide faster way of detecting potential errors and troubleshooting.

**Comment by bersler** [comment]
This feature is complicated to implement.. If there is a demand from users more focus could be given here.

**Comment by sonnguyen-dba** [comment]
Hi Adam,
I hope this so long time. :)

Regards,
Son

**Comment by bersler** [comment]
fixed by last commit in master branch
