### ISSUE TITLE
function KafkaWriter::parseDML

### ISSUE THREAD

**Issue by linanh** [bersler/OpenLogReplicator#7]
In function KafkaWriter::parseDML:
From [KafkaWriter.cpp#L495](https://github.com/bersler/OpenLogReplicator/blob/master/src/KafkaWriter.cpp#L495) to [KafkaWriter.cpp#L504](https://github.com/bersler/OpenLogReplicator/blob/master/src/KafkaWriter.cpp#L504), according variable "redoLogRecord1->object->totalCols" to allocate array.

But in [KafkaWriter.cpp#L828](https://github.com/bersler/OpenLogReplicator/blob/master/src/KafkaWriter.cpp#L828), the table of "redoLogRecord->next" may be different from the table of "redoLogRecord1". Then, the program will be terminated.

**Comment by bersler** [comment]
Thanks @linanh 

I have uploaded fix for this. Now the list of redoLogRecord is checked to refer to the same object pointer to object is taken from the first element of the list.
